### ISSUE TITLE
Togglz console is not displayed after updating togglz version

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz-samples#7]
The togglz-console is not available after updating the togglz-version.
Changing the togglz-spring-boot-starter to togglz-legacy-spring-boot-starter which should be the correct one to run Spring Boot 1.5.X applications doesn't fix this issue.

We should also add some integration tests to fail faster.

**Comment by bennetelli** [comment]
fixed in #8

**Comment by gsteinacker** [comment]
This is not a fix, because it is only working with Spring Boot 1.5.x. The top-level pom.xml is using <spring-boot.version>1.5.22.RELEASE</spring-boot.version>

**Comment by bennetelli** [comment]
yes, I know. It's a fix for the Spring Boot 1.5 only. Wanted to fix the current commited version of togglz-samples as sooon as possible. 

Ok, let's just keep this issue open and I will fix it for Spring Boot 2.X as well ;-)

**Comment by bennetelli** [comment]
the togglz console is available at: http://localhost:8080/togglz-console/index
and the actuator endpoints are available at: http://localhost:8080/actuator/togglz

so this issue seems to be fixed.
